name: Feed → Discord (multi-webhook)

on:
  schedule:
    - cron: "*/10 * * * *" # 10分おき（5分にしたい時は */5 に）
  workflow_dispatch: {}

permissions:
  contents: write # state.json をコミットするため

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3] # 4分割で並列処理
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install feedparser pyyaml requests

      - name: Run fetcher (matrix shard)
        env:
          SHARD_INDEX: ${{ matrix.shard }}
          SHARD_TOTAL: 4
          # 予備の既定（すべてここに落ちる設定があれば使う）
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # チャンネル別（news / yt / x）
          DISCORD_WEBHOOK_NEWS: ${{ secrets.DISCORD_WEBHOOK_NEWS }}
          DISCORD_WEBHOOK_YT: ${{ secrets.DISCORD_WEBHOOK_YT }}
          DISCORD_WEBHOOK_X: ${{ secrets.DISCORD_WEBHOOK_X }}
          DISCORD_WEBHOOK_XKW: ${{ secrets.DISCORD_WEBHOOK_XKW }}
        run: python fetch_and_post.py

      - name: Save state (commit back)
        if: always()
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add state.json
          git commit -m "update state [skip ci]" || echo "no changes"
          git push
